services:
  anvil:
    image: ghcr.io/foundry-rs/foundry
    container_name: anvil
    environment:
      ANVIL_IP_ADDR: "0.0.0.0"
    working_dir: /anvil
    ports:
      - "8545:8545"
    command: anvil --hardfork prague
  server:
    build:
      context: ./frontend
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
